name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install cmocka
      run: sudo apt-get install libcmocka-dev
    - name: check cmocka
      run: file /usr/lib/x86_64-linux-gnu/libcmocka.so.*
    - name: make
      run: make
    - name: Test
      run: ./tests
